name: ✨ Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: Is your feature request related to a problem? Describe it.
      placeholder: I'm always frustrated when I can't export my expenses to CSV...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you've thought about?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low — nice to have
        - Medium — would improve UX significantly
        - High — blocking or critical
    validations:
      required: true
